USE sakila;

SHOW tables;

# 1. Calculate the total revenue
select SUM(amount) AS total_revenue
 from payment;
 
 #2. calculate the average payment amount.
 select avg(amount) AS average_payment
 from payment;
 
 #3. Find the highest payment received.
 Select MAX(amount) AS Highest_Payment
	from payment;
    
#4. Find the lowest payment received.
select MIN(amount) AS Lowest_Payment
	from payment;
    
#5. Calculate total revenue generated by each customer
select customer_id, SUM(amount) 
from payment
GROUP BY customer_id
ORDER BY SUM(amount);

#6. Calculate total revenue generated by each store.
Select * from payment;
Select * from store;
select * from customer;

select c.store_id, Sum(amount)
from store s
join customer c
on s.store_id = c.store_id
join payment p
on p.customer_id = c.customer_id
group by store_id;

#7. Calculate the monthly revenue.
Select 
	Year(payment_date) AS year,
    Month(payment_Date) AS month,
    SUM(amount) AS Revenue
    from payment
    group by year(payment_date), month(payment_date)    
    ORDER BY year(payment_date), month(payment_date);
    
#8. Find the top 10 customers by revenue.
SELECT 
	c.customer_id,
    c.first_name, 
    c.last_name, 
    SUM(p.amount) AS Revenue
FROM payment p
JOIN customer c
	ON p.customer_id = c.customer_id
GROUP BY c.customer_id
ORDER BY Revenue DESC
LIMIT 10;

#9. Find the customers who spent more than $150.
SELECT 
	c.customer_id,
    c.first_name, 
    c.last_name, 
    SUM(p.amount) AS Revenue
FROM payment p
JOIN customer c
	ON p.customer_id = c.customer_id
GROUP BY c.customer_id
HAVING SUM(p.amount) > 150; 